dist: trusty
language: node_js
git:
  depth: 3
node_js:
  - "6"
  - "8"
deploy:
  provider: surge
  project: ./docs
  domain: incredible-hope.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
